### ISSUE TITLE
Help building this project

### ISSUE THREAD

**Issue by nihonjin98** [kursancew/actron-air-wifi#1]
Hi I hope you are still online and checking this project but just wondering if you have any wiring diagrams and or photos of your project to show how it all works.  I have an Action Air ducted air conditioner and looking to turn it into a smart system that doesnt cost an arm and a leg.  Just checking if you are still using it and if you are able to assist should any help be required.  Thanks.

**Comment by L1qu1d1c3** [comment]
+1! would love to see the wiring diagram and how you integrated it...

**Comment by roastcom** [comment]
Has anyone made any progress on the hardware?

**Comment by kursancew** [comment]
I don't have that unit anymore but I drew a diagram of the top of my head and added it to the repo, hope it helps
